id: app_6.2.1
name: Prepare Environment for Manual Testing
status: PENDING
type: MANUAL
depends_on:
- app_5.4.4
- app_1.5.1
- app_1.1.4
manual_instructions:
- '- Ensure the development container is running.

  - Install the package in editable mode: `pip install -e .`.

  - Verify the `.env` file contains a valid `OPENAI_API_KEY`.'
outputs:
- Package installed editable in container.
- API key confirmed present for testing.
