id: app_5.4.2
name: Review Console Script TOML Snippet
status: PENDING
type: MANUAL
depends_on:
- app_5.4.1
manual_instructions:
- "Manually review the TOML snippet:\n  - Check `[project.scripts]` table and mapping\
  \ syntax."
outputs:
- TOML snippet reviewed and approved/corrected.
