id: app_1.4.2
name: Verify Initial Dependencies
status: PENDING
type: MANUAL
depends_on:
- app_1.4.1
manual_instructions:
- Inside the container, run `pip list` to confirm base deps are installed.
outputs:
- Base dependencies present in venv.
